### ISSUE TITLE
Watermark file loader fails

### ISSUE THREAD

**Issue by victor-vanherpt** [tibor95/phatch-python2.7#3]
```
phatch-python2.7]$ ./run.sh 
/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")

(phatch.py:5975): Gtk-WARNING **: Theme parsing error: <data>:1:65: Expected ')' in color definition

(phatch.py:5975): Gtk-WARNING **: Theme parsing error: <data>:1:65: Expected ')' in color definition
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 16762, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/victor/phatch-github/phatch-python2.7/phatch/lib/pyWx/popup.py", line 364, in OnChange
    icon_size=self.icon_size,
  File "/home/victor/phatch-github/phatch-python2.7/phatch/lib/pyWx/imageFileBrowser.py", line 102, in __init__
    self.image_list = ListCtrl(self.panel, files, icon_size)
  File "/home/victor/phatch-github/phatch-python2.7/phatch/lib/pyWx/imageFileBrowser.py", line 54, in __init__
    pil_wxBitmap(open_thumb(file, size=icon_size)))
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 6735, in Add
    return _gdi_.ImageList_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "(bitmap.GetWidth() >= m_width && bitmap.GetHeight() == m_height) || (m_width == 0 && m_height == 0)" failed at ./src/generic/imaglist.cpp(66) in Add(): invalid bitmap size in wxImageList: this might work on this platform but definitely won't under Windows.
```

Same happens with "original" versions...

**Comment by tibor95** [comment]
Can you navigate me how to invoke this issue? I am not familiar with that watermark file loading stuff...
